apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b2qnk0ugn-python
  janus-idp.io/tekton: b2qnk0ugn-python
  backstage.io/kubernetes-id: b2qnk0ugn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b2qnk0ugn-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
