apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b2qnk0ugn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b2qnk0ugn-python 
  name: b2qnk0ugn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b2qnk0ugn-python 
