apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b2qnk0ugn-python 
  janus-idp.io/tekton: b2qnk0ugn-python
  backstage.io/kubernetes-id: b2qnk0ugn-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b2qnk0ugn-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml